Added: various additions.

diff --git a/templates/sv/run b/templates/sv/run
--- a/templates/sv/run
+++ b/templates/sv/run
@@ -4,9 +4,15 @@
 set -u -e
 exec 2>&1
 
-dir={{DIR}}
-bin="$dir/bin/{{NAME}}"
+dir={{DEPLOY_DIR}}/{{NAME}}
+
 
 cd "$dir"
-echo "=== Starting $bin"
-exec chpst -u stager -U stager "$bin" deploy watch
+release="$(find . -maxdepth 1 -mindepth 1 -type d | sort | tail -n 1)"
+
+test -d "$release" || { echo "!!! latest release not found in $dir" >&2; exit 1; }
+
+cd "$release"
+bin="bin/{{NAME}}"
+echo "=== Starting @ $(date): $bin service run"
+exec chpst -u stager -U stager "$bin" service run
